### ISSUE TITLE
Investigate project and figure out subtasks

### ISSUE THREAD

**Issue by ivonasto** [ivonasto/rust-calculator#2]

**Comment by ivonasto** [comment]
- [ ] deploy app as is 
- [ ] claim issue + ask how change of lang will happen
- [ ] research flutter localization 
- [ ] substitute a single page and test
- [ ] config file - BG/ EN
- [ ] substitute all pages 
     - [ ] find all pages and list them
     - [ ] substitute
     - [ ] test
- [ ] contact to add EN/BG button
